### ISSUE TITLE
My saved published project not the same when viewed?

### ISSUE THREAD

**Issue by marmilicious** [phptuts/fastled-animator#11]
I made a project, saved it, and made it public. But if I go to Projects and View it, it seems to be showing old data from when I initially was working on it, not the currently saved version.

**Comment by marmilicious** [comment]
Hmmm I'm now thinking this was a page reload sort of issue. Where I was seeing old pixel data before seems correct now. I had closed and reopened things since I put this issue in so that seems to fit what I'm seeing. 
And just now I made an edit to my project description text, saved and then went to Projects section and Viewed my project and it was still the old text until I did a page reload.

**Comment by phptuts** [comment]
That's super helpful. I should be able to reproduce that and see if I can fix it.

**Comment by phptuts** [comment]
I think this one is fixed.  Thank you!

**Comment by marmilicious** [comment]
Closing for now. Will reopen later if I still see some oddness. Thank you

**Comment by phptuts** [comment]
Thank you!
