### ISSUE TITLE
Me page UI suggestion

### ISSUE THREAD

**Issue by marmilicious** [phptuts/fastled-animator#12]
When I first went to the Me page, the name field and Save button didn't even register to me since it was almost the full page width. I think I thought the Save button was a page section divider of some sort.  Here's a UI change suggestion.

![SNAG-0031](https://user-images.githubusercontent.com/8573409/193761083-418989fb-70c5-4be4-90cc-93c20e22aa29.jpg)

**Comment by phptuts** [comment]
This one ready for QA.  I think I got it pretty close
