### ISSUE TITLE
Can Select and Unselect be combined?

### ISSUE THREAD

**Issue by marmilicious** [phptuts/fastled-animator#8]
I was wondering if the Select and Unselect buttons could be combined?  Then when clicking it would select, or unselect, based on if the pixel was already selected or not.

**Comment by phptuts** [comment]
I think that's a good idea. I am gonna work on the save bug first, but I will circle back around!

**Comment by phptuts** [comment]
This one will be a little tougher because of the drag and select.  Do you have any idea how you would do that?  The problem is that a mouseover event is triggered multiple times a second.

**Comment by phptuts** [comment]
I think I need to use the mouse enter event to get this to work.  I will test it out tonight and see what it looks like.

**Comment by phptuts** [comment]
@marmilicious So made a prototype of what this feature might look like.  Can you play around with it and let me know what you think.

https://fastled-animator-111v-g76fak2ps-phptuts.vercel.app/create

**Comment by marmilicious** [comment]
This seems to work nicely. 
Only thing I'm noticing is if you click and hold the mouse button and drag across it doesn't do anything with the pixel you started on, only the others that you drag across.

**Comment by phptuts** [comment]
So I think I got this fixed.  I also fixed #13 this issue as well.

https://fastled-animator-111v-l2v6vnyyd-phptuts.vercel.app/create

Let me know what you think

Thank you!

**Comment by marmilicious** [comment]
Working! Thank you
